apiVersion: tekton.dev/v1beta1
kind: ClusterTask
metadata:
  name: argocd-branch-sync
  labels:
    # Version de la ClusterTask
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Deployment
    tekton.dev/tags: argocd, branch, sync
    tekton.dev/displayName: "ArgoCD branch Sync"
spec:
  params:
    - name: application-name
      description: name of the application to sync
    - name: target-branch
      description: uri of the new image
    - name: flags
      default: --
  stepTemplate:
    name: config
    envFrom:
      - configMapRef:
          name: argocd-env-configmap  # used for server address
      - secretRef:
          name: argocd-env-secret  # used for authentication (username/password or auth token)
  steps:
    - name: branch-sync
      image: quay.io/argoproj/argocd:v2.2.8
      script: |
        if [ -z "$ARGOCD_AUTH_TOKEN" ]; then
          yes | argocd login "$ARGOCD_SERVER" --username="$ARGOCD_USERNAME" --password="$ARGOCD_PASSWORD";
        fi
        argocd app set "$(params.application-name)" --revision="$(params.target-branch)" "$(params.flags)"
        argocd app sync "$(params.application-name)" "$(params.flags)"
        argocd app wait "$(params.application-name)" --health "$(params.flags)"